<template>
  <div class="container main">
    <div class="home tag">
      <span>Home</span>
    </div>
    <div class="animation">
      <svg id="レイヤー_1" data-name="レイヤー 1" class="abc" :class="className" xmlns="http://www.w3.org/2000/svg" >
        <polyline class="cls-1 svg-elem-1" points="389.54 352.5 411.02 352.5 1367 352.5"></polyline>
        <g class="cls-2">
          <line class="cls-3 svg-elem-2" x1="-1266" y1="257.5" x2="0.5" y2="257.5"></line>
        </g>
        <polygon class="cls-4 svg-elem-3" points="388.54 350.5 288.92 563.18 284.24 573.18 293.59 599 293.61 598.99 298.28 589.02 410.02 350.5 388.54 350.5"></polygon>
        <polygon class="cls-4 svg-elem-4" points="298.31 589.35 288.93 564.36 155.15 207.94 150.19 206.86 148.34 211.99 151.07 219.25 284.24 574.03 293.61 599 293.63 598.99 298.31 589.35"></polygon>
        <polygon class="cls-4 svg-elem-5" points="154.67 207.92 150.88 219 106 350.07 104.48 354.52 99.51 354.52 101.74 348 148.34 211.89 150.06 206.86 154.67 207.92"></polygon>
        <polygon class="cls-4 svg-elem-6" points="104.48 354.52 99.51 354.52 0.18 354.52 0.18 348 101.74 348 106 348 106 350.07 104.48 354.52"></polygon>
        <text class="cls-5" transform="translate(511.73 343.94)">Member</text>
      </svg>
    </div>
    <div class="container1">
      <div class="container-i-1">
        <img src="../static/IMG_8981.JPG" height="" width="100%">
        <pre>
        <br>代表/豊永雄正
        </pre>
      </div>
      <div class="container-t-1">
        <h2>心が”ゆれる”ものを創る</h2>
        <br>
        <p>
          2020年9月16日、チームInovange『（イノベンジ）』を結成致しました。現在、メンバーは5人。僕自身の信念でもある”心がゆれるものを創る”を1つの理念として掲げております。<br><br>僕にとって、”ゆれる”は”つながる”であり、”革新”の意味。幼い頃から地元の福井で経験してきた人と”つながる”感覚。そして、TVや本、音楽を通して見続け、憧れ続けてきた”革新”。それらを表現していきます。まずは、広告やwebページを通してお客様とそのお客様を”つないで”いきます。
        </p>
      </div>
    </div>
    <div class="container2">
      <div class="container-i-2">
        <img src="/IMG_8946.JPG" height="200px" width="">
      </div>
      <div class="container-t-2">
        <p>アイウエオ</p>
      </div>
    </div>
    <div class="container3">
      <div class="container-i-3">
        <img src="/IMG_8981.JPG" height="200px" width="">
      </div>
      <div class="container-t-3">
        <p>アイウエオ</p>
      </div>
    </div>
    <div class="container4">
      <div class="container-i-4">
        <img src="../static/IMG_8981.JPG" height="200px" width="">
      </div>
      <div class="container-t-4">
        <p>アイウエオ</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      active: false
    }
  },
  computed: {
    className () {
      return {
        active: this.active
      }
    }
  },
  mounted () {
    setTimeout(() => {
      this.active = true
    }, 50)
  }
}
</script>

<style>
.cls-1 {
  fill: #9a0010;
}

.cls-1, .cls-2, .cls-3 {
  stroke: #9a0010;
  stroke-miterlimit: 10;
}

.cls-1, .cls-2 {
  stroke-width: 1.51px;
}

.cls-2 {
  fill: #040000;
}

.cls-3 {
  fill: none;
  stroke-width: 2.24px;
}

.cls-4 {
  font-size: 66.4px;
  fill: #231815;
  font-family: KozGoPr6N-Regular-83pv-RKSJ-H, Kozuka Gothic Pr6N;
  letter-spacing: 0.18em;
}

span {
  border: 1px solid;
  border-color: #35495e;
}

.container-i-1 {
  width: 40%;
  float: left;
}

.container-t-1 {
  width: 50%;
  float: left;
  margin-left: 30px;
}

.container1 {
  margin: auto;
  margin-bottom: 140px;
  width: 100%;
  height: 400px;
}

.container-i-2 {
  width: 50%;
  float: left;
}

.container-t-2 {
  width: 50%;
  float: left;
}

.container2 {
  margin: auto;
  margin-bottom: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.container-i-3 {
  width: 50%;
  float: left;
}

.container-t-3 {
  width: 50%;
  float: left;
}

.container3 {
  margin: auto;
  margin-bottom: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.container-i-4 {
  width: 50%;
  float: left;
}

.container-t-4 {
  width: 50%;
  float: left;
}

.container4 {
  margin: auto;
  margin-bottom: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.abc {
  width: 100%;
  height: 700px;
  position: absolute;
  top: 50%;
  left: 45%;
  transform: translate(-50%, -50%);
}

.animation {
  width: 1200px;
  height: 700px;
  position: relative;
}

/***************************************************
 * Generated by SVG Artista on 11/22/2020, 11:01:54 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

svg .svg-elem-1 {
  stroke-dashoffset: 979.4599609375px;
  stroke-dasharray: 979.4599609375px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
}

svg.active .svg-elem-1 {
  stroke-dashoffset: 0;
}

svg .svg-elem-2 {
  stroke-dashoffset: 1268.5px;
  stroke-dasharray: 1268.5px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
}

svg.active .svg-elem-2 {
  stroke-dashoffset: 0;
}

svg .svg-elem-3 {
  stroke-dashoffset: 571.2650146484375px;
  stroke-dasharray: 571.2650146484375px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
}

svg.active .svg-elem-3 {
  stroke-dashoffset: 0;
  fill: rgb(154, 0, 16);
}

svg .svg-elem-4 {
  stroke-dashoffset: 844.03662109375px;
  stroke-dasharray: 844.03662109375px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
}

svg.active .svg-elem-4 {
  stroke-dashoffset: 0;
  fill: rgb(154, 0, 16);
}

svg .svg-elem-5 {
  stroke-dashoffset: 322.7267761230469px;
  stroke-dasharray: 322.7267761230469px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
}

svg.active .svg-elem-5 {
  stroke-dashoffset: 0;
  fill: rgb(154, 0, 16);
}

svg .svg-elem-6 {
  stroke-dashoffset: 225.41241455078125px;
  stroke-dasharray: 225.41241455078125px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s;
}

svg.active .svg-elem-6 {
  stroke-dashoffset: 0;
  fill: rgb(154, 0, 16);
}

.cls-1, .cls-3 {
  fill: none;
  stroke: #9a0010;
  stroke-miterlimit: 10;
}

.cls-1 {
  stroke-width: 10.24px;
}

.cls-2 {
  opacity: 0.3;
}

.cls-3 {
  stroke-width: 7px;
}

.cls-4 {
  fill: #9a0010;
  fill-rule: evenodd;
}

.cls-5 {
  font-size: 87px;
  fill: #231815;
  font-family: KozGoPr6N-Regular-83pv-RKSJ-H, Kozuka Gothic Pr6N;
}
</style>
