<template>
  <div class="container main">
    <div class="home tag">
      <span>Home</span>
    </div>

    <svg id="レイヤー_1" data-name="レイヤー 1" class="レイヤー１" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <style>.cls-1 {
          fill: #9a0010;
          }

          .cls-1, .cls-2, .cls-3 {
          stroke: #9a0010;
          stroke-miterlimit: 10;
          }

          .cls-1, .cls-2 {
          stroke-width: 1.51px;
          }

          .cls-2 {
          fill: #040000;
          }

          .cls-3 {
          fill: none;
          stroke-width: 2.24px;
          }

          .cls-4 {
          font-size: 66.4px;
          fill: #231815;
          font-family: KozGoPr6N-Regular-83pv-RKSJ-H, Kozuka Gothic Pr6N;
          letter-spacing: 0.18em;
          }</style>
      </defs>
      <path class="cls-1 svg-elem-1" d="M466.82,394.74C654.05,593.16,841.68,631.63,1030,396.09" />
      <path class="cls-2 svg-elem-2" d="M102.62,392.39c103.29-186.74,225.8-135.29,355.2,1.35" />
      <line class="cls-3 svg-elem-3" x1="-134" y1="394" x2="1309" y2="394" />
      <text class="cls-4" transform="translate(457.57 375.81)">Member</text>
    </svg>

    <div class="container1">
      <div class="container-i-1">
        <img src="../static/IMG_8981.JPG" height="200px" width="">
      </div>
      <div class="container-t-1">
        <p>アイウエオ</p>
      </div>
    </div>

    <div class="container2">
      <div class="container-i-2">
        <img src="../static/IMG_8946.JPG" height="200px" width="">
      </div>
      <div class="container-t-2">
        <p>アイウエオ</p>
      </div>
    </div>

    <div class="container3">
      <div class="container-i-3">
        <img src="../static/IMG_8981.JPG" height="200px" width="">
      </div>
      <div class="container-t-3">
        <p>アイウエオ</p>
      </div>
    </div>

    <div class="container4">
      <div class="container-i-4">
        <img src="../static/IMG_8981.JPG" height="200px" width="">
      </div>
      <div class="container-t-4">
        <p>アイウエオ</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {}
</script>

<style>
span {
  border: 1px solid;
  border-color: #35495e;
}

h1 {
  position: absolute;
  left: 50%;
  top: 50%;
  font-size: 50px;
  transform: translate(-50%, -50%);
}

.containert {
}

.container-i-1 {
  width: 50%;
  float: left;
}

.container-t-1 {
  width: 50%;
  float: left;
}

.container1 {
  margin: auto;
  margin-bottom: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.container-i-2 {
  width: 50%;
  float: left;
}

.container-t-2 {
  width: 50%;
  float: left;
}

.container2 {
  margin: auto;
  margin-bottom: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.container-i-3 {
  width: 50%;
  float: left;
}

.container-t-3 {
  width: 50%;
  float: left;
}

.container3 {
  margin: auto;
  margin-bottom: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.container-i-4 {
  width: 50%;
  float: left;
}

.container-t-4 {
  width: 50%;
  float: left;
}

.container4 {
  margin: auto;
  margin-bottom: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.レイヤー１ {
  viewBox: 0 0 1200 700;
  width: 100%;
  height: 700px;

}

/***************************************************
 * Generated by SVG Artista on 11/6/2020, 8:17:01 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 673.2532348632812px;
    stroke-dasharray: 673.2532348632812px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 673.2532348632812px;
    stroke-dasharray: 673.2532348632812px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(154, 0, 16);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(154, 0, 16);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
  animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
  animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
  animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
}

@-webkit-keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 449.749267578125px;
    stroke-dasharray: 449.749267578125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 449.749267578125px;
    stroke-dasharray: 449.749267578125px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(4, 0, 0);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(4, 0, 0);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
  animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
  animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
  animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
}

@-webkit-keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 1445px;
    stroke-dasharray: 1445px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

@keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 1445px;
    stroke-dasharray: 1445px;
  }

  100% {
    stroke-dashoffset: 0;
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
  animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
  animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
  animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
}

</style>
