<template>
  <div class="container main">
    <div class="home tag">
      <span>Home</span>
    </div>

    <div class="containert">
      <svg id="レイヤー_1" data-name="レイヤー 1" class="abc" :class="className" xmlns="http://www.w3.org/2000/svg">
        <line class="cls-1 svg-elem-1" y1="350.5" x2="401.5" y2="350.5"/>
        <g class="cls-2">
          <line class="cls-3 svg-elem-2" x1="798" y1="349" x2="1200" y2="349"/>
        </g>
        <line class="cls-4 svg-elem-3" x1="476.5" y1="205.5" x2="748.5" y2="447.5"/>
        <line class="cls-4 svg-elem-4" x1="798.5" y1="349.5" x2="748.5" y2="447.5"/>
        <line class="cls-4 svg-elem-5" x1="476.5" y1="205.5" x2="401.5" y2="350.5"/>
        <text class="cls-5" transform="translate(372.86 378.52)">Portfolio</text>
      </svg>
    </div>

    <div class="container1">
      <div class="container-i-1">
        <img src="../../Documents/4x/アートボード 3@4x-80.jpg" height="" width="200px"/>
      </div>
      <div class="container-t-1">
        <p>アイウエオ</p>
      </div>
    </div>
    <div class="container2">
      <img src="../../../../Applications/キトクル/ポスティングチラシX.jpg" height="" width="300px"/>
    </div>
    <div class="container3">
      <img src="../../Creative Cloud Files/4x/4x/アートボード 1@4x-80.jpg" height="" width="300px"/>
    </div>
    <div class="container4">
      <img src="../../Creative Cloud Files/4x/アートボード 3@4x.png" height="" width="300px"/>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      active: false
    }
  },
  computed: {
    className () {
      return {
        active: this.active
      }
    }
  },
  mounted () {
    setTimeout(() => {
      this.active = true
    }, 50)
  }
}
</script>

<style>
span {
  border: 1px solid #35495e;
}

h1 {
}

.containert {
  width: 1200px;
  height: 700px;
  position: relative;
}

.container-i-1 {
  width: 50%;
  float: left;
}

.container-t-1 {
  width: 50%;
  float: left;
}

.container1 {
  margin: auto;
  margin-top: 140px;
  border: 2px solid black;
  width: 100%;
  height: 400px;
}

.container2 {
  margin-top: 100px;
  border: 2px solid black;
  width: auto;
  height: 400px;
}

.container3 {
  margin-top: 100px;
  border: 2px solid black;
  width: auto;
  height: 400px;
}

.container4 {
  margin-top: 100px;
  border: 2px solid black;
  width: auto;
  height: 400px;
}

/***************************************************
 * Generated by SVG Artista on 11/8/2020, 7:09:58 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

svg .svg-elem-1 {
  stroke-dashoffset: 403.5px;
  stroke-dasharray: 403.5px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
}

svg.active .svg-elem-1 {
  stroke-dashoffset: 0;
  fill: rgb(255, 255, 255);
}

svg .svg-elem-2 {
  stroke-dashoffset: 404px;
  stroke-dasharray: 404px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
}

svg.active .svg-elem-2 {
  stroke-dashoffset: 0;
}

svg .svg-elem-3 {
  stroke-dashoffset: 366.0714111328125px;
  stroke-dasharray: 366.0714111328125px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
}

svg.active .svg-elem-3 {
  stroke-dashoffset: 0;
}

svg .svg-elem-4 {
  stroke-dashoffset: 112.01818084716797px;
  stroke-dasharray: 112.01818084716797px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
}

svg.active .svg-elem-4 {
  stroke-dashoffset: 0;
}

svg .svg-elem-5 {
  stroke-dashoffset: 165.24827575683594px;
  stroke-dasharray: 165.24827575683594px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s;
}

svg.active .svg-elem-5 {
  stroke-dashoffset: 0;
}

.abc {
  width: 100%;
  height: 700px;
  position: absolute;
  top: 50%;
  left: 45%;
  transform: translate(-50%, -50%);
}

.animation {
  width: 1200px;
  height: 700px;
  position: relative;
}

.cls-1 {
  fill: #fff;
}

.cls-1, .cls-3, .cls-4 {
  stroke: #9a0010;
  stroke-miterlimit: 10;
  stroke-width: 4px;
}

.cls-1, .cls-2, .cls-4 {
  opacity: 0.4;
}

.cls-3, .cls-4 {
  fill: none;
}

.cls-5 {
  font-size: 120px;
  fill: #4d4d4d;
  font-family: Futura-Medium, Futura;
  font-weight: 500;
}
</style>
