<template>
  <div class="container main">
    <div class="home tag">
      <span>Home</span>
    </div>

    <div class="containert">
      <svg id="レイヤー_1" data-name="レイヤー 1" class="abc" :class="className" xmlns="http://www.w3.org/2000/svg" >
        <path class="cls-1 svg-elem-1" d="M786.05,348.83l-.28.48c-19.35,34-93.27,153-192,121.41-61.4-19.65-104-88.45-123.64-125.21"></path>
        <path class="cls-2 svg-elem-2" d="M115.32,350.67c.09-.17.19-.33.29-.49,22-36.83,106.22-165.66,218.64-131.46C404.17,240,452.65,314.5,475.05,354.3"></path>
        <polyline class="cls-3 svg-elem-3" points="116.93 351.34 0.38 351.34 0.38 350.86 117.22 350.86"></polyline>
        <polyline class="cls-4 svg-elem-4" points="784.24 348.83 1341.2 348.83 1366 348.83 1366 348.98 1357.15 349.31 1328.21 349.31 783.17 349.31"></polyline>
        <text class="cls-5" transform="translate(824.29 333.72)">Works</text>
      </svg>
    </div>

    <div class="container1">
      <img src="../static/アートボード 2@4x-80.jpg" height="100%" width="100%"/></div>
    <div class="container2">
      <img src="../static/クリエイターコース　ワードウルフ_アートボード 1.png" height="100%" width="100%"/>
    </div>
    <div class="container3">
      <img src="../../Creative Cloud Files/4x/4x/アートボード 1@4x-80.jpg" height="" width="300px"/>
    </div>
    <div class="container4">
      <img src="../../Creative Cloud Files/4x/アートボード 3@4x.png" height="" width="100%"/>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      active: false
    }
  },
  computed: {
    className () {
      return {
        active: this.active
      }
    }
  },
  mounted () {
    setTimeout(() => {
      this.active = true
    }, 50)
  }
}
</script>

<style>
span {
  border: 1px solid #35495e;
}

h1 {
}

.containert {
  width: 1200px;
  height: 700px;
  position: relative;
}

.container1 {
  margin: auto;
  margin-top: 140px;
  width: 100%;
}

.container2 {
  margin-top: 100px;
  border: 2px solid black;
  width: auto;
  height: 400px;
}

.container3 {
  margin-top: 100px;
  border: 2px solid black;
  width: auto;
  height: 400px;
}

.container4 {
  width: auto;
  height: 400px;
}

.abc {
  width: 100%;
  height: 700px;
  position: absolute;
  top: 50%;
  left: 45%;
  transform: translate(-50%, -50%);
}

.animation {
  width: 1200px;
  height: 700px;
  position: relative;
}

/***************************************************
 * Generated by SVG Artista on 11/22/2020, 11:23:20 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

svg .svg-elem-1 {
  stroke-dashoffset: 428.62420654296875px;
  stroke-dasharray: 428.62420654296875px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s;
}

svg.active .svg-elem-1 {
  stroke-dashoffset: 0;
}

svg .svg-elem-2 {
  stroke-dashoffset: 477.76416015625px;
  stroke-dasharray: 477.76416015625px;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s;
}

svg.active .svg-elem-2 {
  stroke-dashoffset: 0;
}

svg .svg-elem-3 {
  stroke-dashoffset: 235.87002563476562px;
  stroke-dasharray: 235.87002563476562px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s;
}

svg.active .svg-elem-3 {
  stroke-dashoffset: 0;
  fill: rgb(154, 0, 16);
}

svg .svg-elem-4 {
  stroke-dashoffset: 1166.7462158203125px;
  stroke-dasharray: 1166.7462158203125px;
  fill: transparent;
  -webkit-transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
  transition: stroke-dashoffset 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s,
  fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s;
}

svg.active .svg-elem-4 {
  stroke-dashoffset: 0;
  fill: rgb(154, 0, 16);
}

.cls-1, .cls-2 {
  fill: none;
}

.cls-1, .cls-2, .cls-3, .cls-4 {
  stroke: #9a0010;
  stroke-miterlimit: 10;
}

.cls-1 {
  stroke-width: 9.3px;
}

.cls-2 {
  stroke-width: 8.8px;
}

.cls-3, .cls-4 {
  fill: #9a0010;
  fill-rule: evenodd;
}

.cls-3 {
  stroke-width: 5px;
}

.cls-4 {
  stroke-width: 12px;
}

.cls-5 {
  font-size: 87px;
  fill: #231815;
  font-family: KozGoPr6N-Regular-83pv-RKSJ-H, Kozuka Gothic Pr6N;
}
</style>
